#!/bin/bash

#Replace $1 and $2 with your desired numbers and add below lines to your bashrc file.


DISPLAY_DEVICE=`xrandr |grep " connected" | awk {'print $1'}`

sudo xrandr --newmode `cvt $1 $2 |grep Modeline |cut -d ' ' -f 2-`

sudo xrandr --addmode $DISPLAY_DEVICE `cvt $1 $2 |grep Modeline |cut -d ' ' -f 2`
